In [36]:
import pandas as pd
df= pd.read_csv('../data_sets/credito.csv')

In [37]:
(df == 'na').sum()

id                            0
default                       0
idade                         0
sexo                          0
dependentes                   0
escolaridade               1519
estado_civil                749
salario_anual              1112
tipo_cartao                   0
meses_de_relacionamento       0
qtd_produtos                  0
iteracoes_12m                 0
meses_inativo_12m             0
limite_credito                0
valor_transacoes_12m          0
qtd_transacoes_12m            0
dtype: int64

In [38]:
df.replace(["na", "NA", "N/A", "null"], pd.NA, inplace=True)
df.isna().sum()

id                            0
default                       0
idade                         0
sexo                          0
dependentes                   0
escolaridade               1519
estado_civil                749
salario_anual              1112
tipo_cartao                   0
meses_de_relacionamento       0
qtd_produtos                  0
iteracoes_12m                 0
meses_inativo_12m             0
limite_credito                0
valor_transacoes_12m          0
qtd_transacoes_12m            0
dtype: int64

In [39]:
df.dtypes

id                         int64
default                    int64
idade                      int64
sexo                         str
dependentes                int64
escolaridade                 str
estado_civil                 str
salario_anual                str
tipo_cartao                  str
meses_de_relacionamento    int64
qtd_produtos               int64
iteracoes_12m              int64
meses_inativo_12m          int64
limite_credito               str
valor_transacoes_12m         str
qtd_transacoes_12m         int64
dtype: object

In [40]:
df.head()

,id,default,idade,sexo,dependentes,escolaridade,estado_civil,salario_anual,tipo_cartao,meses_de_relacionamento,qtd_produtos,iteracoes_12m,meses_inativo_12m,limite_credito,valor_transacoes_12m,qtd_transacoes_12m
0,768805383,0,45,M,3,ensino medio,casado,$60K - $80K,blue,39,5,3,1,"12.691,51","1.144,90",42
1,818770008,0,49,F,5,mestrado,solteiro,menos que $40K,blue,44,6,2,1,"8.256,96","1.291,45",33
2,713982108,0,51,M,3,mestrado,casado,$80K - $120K,blue,36,4,0,1,"3.418,56","1.887,72",20
3,769911858,0,40,F,4,ensino medio,NaN,menos que $40K,blue,34,3,1,4,"3.313,03","1.171,56",20
4,709106358,0,40,M,3,sem educacao formal,casado,$60K - $80K,blue,21,5,0,1,"4.716,22","816,08",28

In [41]:
df.estado_civil.mode()

0    casado
Name: estado_civil, dtype: str

In [42]:
df['escolaridade'] = df['escolaridade'].fillna(df['escolaridade'].mode)
df['estado_civil'] = df['estado_civil'].fillna(df['estado_civil'].mode)
df['salario_anual'] = df['salario_anual'].fillna(df['salario_anual'].mode)
df.isna().sum()

id                         0
default                    0
idade                      0
sexo                       0
dependentes                0
escolaridade               0
estado_civil               0
salario_anual              0
tipo_cartao                0
meses_de_relacionamento    0
qtd_produtos               0
iteracoes_12m              0
meses_inativo_12m          0
limite_credito             0
valor_transacoes_12m       0
qtd_transacoes_12m         0
dtype: int64

In [43]:
df.head()

,id,default,idade,sexo,dependentes,escolaridade,estado_civil,salario_anual,tipo_cartao,meses_de_relacionamento,qtd_produtos,iteracoes_12m,meses_inativo_12m,limite_credito,valor_transacoes_12m,qtd_transacoes_12m
0,768805383,0,45,M,3,ensino medio,casado,$60K - $80K,blue,39,5,3,1,"12.691,51","1.144,90",42
1,818770008,0,49,F,5,mestrado,solteiro,menos que $40K,blue,44,6,2,1,"8.256,96","1.291,45",33
2,713982108,0,51,M,3,mestrado,casado,$80K - $120K,blue,36,4,0,1,"3.418,56","1.887,72",20
3,769911858,0,40,F,4,ensino medio,<bound method Series.mode of 0 casa...,menos que $40K,blue,34,3,1,4,"3.313,03","1.171,56",20
4,709106358,0,40,M,3,sem educacao formal,casado,$60K - $80K,blue,21,5,0,1,"4.716,22","816,08",28

In [44]:
df['limite_credito'] = df['limite_credito'].str.replace({'.':'', ',': '.'}) 
df['valor_transacoes_12m'] = df['valor_transacoes_12m'].str.replace({'.':'', ',': '.'}) 
df['salario_anual'] = df['salario_anual'].str.replace({'$':'', 'K': '000', 'menos que': '0 -'})

In [45]:
df.head()

,id,default,idade,sexo,dependentes,escolaridade,estado_civil,salario_anual,tipo_cartao,meses_de_relacionamento,qtd_produtos,iteracoes_12m,meses_inativo_12m,limite_credito,valor_transacoes_12m,qtd_transacoes_12m
0,768805383,0,45,M,3,ensino medio,casado,60000 - 80000,blue,39,5,3,1,12691.51,1144.90,42
1,818770008,0,49,F,5,mestrado,solteiro,0 - 40000,blue,44,6,2,1,8256.96,1291.45,33
2,713982108,0,51,M,3,mestrado,casado,80000 - 120000,blue,36,4,0,1,3418.56,1887.72,20
3,769911858,0,40,F,4,ensino medio,<bound method Series.mode of 0 casa...,0 - 40000,blue,34,3,1,4,3313.03,1171.56,20
4,709106358,0,40,M,3,sem educacao formal,casado,60000 - 80000,blue,21,5,0,1,4716.22,816.08,28

In [48]:
df['salario_anual'] = df['salario_anual'].fillna(df['salario_anual'].mode)
df.isna().sum()

id                         0
default                    0
idade                      0
sexo                       0
dependentes                0
escolaridade               0
estado_civil               0
salario_anual              0
tipo_cartao                0
meses_de_relacionamento    0
qtd_produtos               0
iteracoes_12m              0
meses_inativo_12m          0
limite_credito             0
valor_transacoes_12m       0
qtd_transacoes_12m         0
dtype: int64

In [50]:
df.to_excel('../data_sets/datos_limpios.xlsx', index= False, sheet_name='hoja_1')